export const FETCH_LAPORAN_REQUEST_USER = `redux/fetch/FETCH_LAPORAN_REQUEST_USER`
export const FETCH_LAPORAN_REQUEST_SUCCESS_USER = `redux/fetch/FETCH_LAPORAN_REQUEST_SUCCESS_USER`
export const FETCH_LAPORAN_REQUEST_ERROR_USER = 'redux/fetch/FETCH_LAPORAN_REQUEST_ERROR_USER'