export const KOMENTAR_CREATE_REQUEST = 'redux/fetch/KOMENTAR_CREATE_REQUEST';
export const KOMENTAR_CREATE_SUCCESS = 'redux/fetch/KOMENTAR_CREATE_SUCCESS';
export const KOMENTAR_CREATE_FAIL = 'redux/fetch/KOMENTAR_CREATE_FAIL';

export const KOMENTAR_DELETE_REQUEST = 'redux/fetch/KOMENTAR_DELETE_REQUEST';
export const KOMENTAR_DELETE_SUCCESS = 'redux/fetch/KOMENTAR_DELETE_SUCCESS';
export const KOMENTAR_DELETE_FAIL = 'redux/fetch/KOMENTAR_DELETE_FAIL';