export const START_FETCHING_JENISKERUSAKAN = "redux/fetch/START_FETCHING_JENISKERUSAKAN "
export const SUCCESS_FETCHING_JENISKERUSAKAN = "redux/fetch/SUCCESS_FETCHING_JENISKERUSAKAN"
export const ERROR_FETCHING_JENISKERUSAKAN = "redux/fetch/ERROR_FETCHING_JENISKERUSAKAN"