export const FETCH_LAPORAN_VOTE_REQUEST = 'redux/fetch/FETCH_LAPORAN_VOTE_REQUEST'
export const FETCH_LAPORAN_VOTE_SUCCESS = 'redux/fetch/FETCH_LAPORAN_VOTE_SUCCESS'
export const FETCH_LAPORAN_VOTE_FAILURE = 'redux/fetch/FETCH_LAPORAN_VOTE_FAILURE'
export const RESET_FETCH_LAPORAN_VOTE = 'redux/fetch/RESET_FETCH_LAPORAN_VOTE' 