export const DELETE_LAPORAN_REQUEST_USER = 'redux/delete/DELETE_LAPORAN_REQUEST_USER';
export const DELETE_LAPORAN_SUCCESS_USER = 'redux/delete/DELETE_LAPORAN_SUCCESS_USER';
export const DELETE_LAPORAN_ERROR_USER   = 'redux/delete/DELETE_LAPORAN_ERROR_USER';
